In [7]:
import math

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
import statsmodels.formula.api as sm

In [2]:
from statsmodels.tsa import tsatools, stattools

In [3]:
from statsmodels.tsa.arima_model import ARIMA

In [4]:
from statsmodels.graphics import tsaplots

In [31]:
amtrak_df = pd.read_csv('Amtrak.csv')

In [32]:
amtrak_df.head()

    Month  Ridership
0  Jan-91   1708.917
1  Feb-91   1620.586
2  Mar-91   1972.715
3  Apr-91   1811.665
4  May-91   1974.964

In [33]:
amtrak_df.describe()

         Ridership
count   159.000000
mean   1822.197208
std     181.636034
min    1360.852000
25%    1698.564500
50%    1831.049000
75%    1966.957500
max    2223.349000

In [34]:
amtrak_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Month      159 non-null    object
 1   Ridership  159 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.6+ KB

In [35]:
amtrak_df.dtypes

Month         object
Ridership    float64
dtype: object

def fix_date(date_str): 
        if '-' in date_str: 
                parts = date_str.split('-') 
                if len(parts) == 2 and parts[1] == '00': 
                            return f"{parts[0]} 2000" 
        return date_str 
# Apply the function to the 'date' column 
amtrak_df['Month'] = amtrak_df['Month'].apply(fix_date)

In [37]:
amtrak_df['Month'] = pd.to_datetime(amtrak_df['Month'])
amtrak_df['Month'] = pd.to_datetime(amtrak_df['Month']) 
amtrak_df.set_index('Month', inplace=True)

/tmp/ipykernel_11861/1680073187.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  amtrak_df['Month'] = pd.to_datetime(amtrak_df['Month'])

DateParseError: day is out of range for month: Jan-00, at position 108

In [26]:
amtrak_df.dtypes

Month                object
Ridership           float64
Date         datetime64[ns]
dtype: object

In [29]:
amtrak_df.head()

    Month  Ridership Date
0  Jan-91   1708.917  NaT
1  Feb-91   1620.586  NaT
2  Mar-91   1972.715  NaT
3  Apr-91   1811.665  NaT
4  May-91   1974.964  NaT

In [27]:
ridership_ts = pd.Series(amtrak_df.Ridership.values, index=amtrak_df.Date)

In [28]:
ridership_ts

Date
NaT    1708.917
NaT    1620.586
NaT    1972.715
NaT    1811.665
NaT    1974.964
         ...
NaT         NaN
NaT         NaN
NaT         NaN
NaT         NaN
NaT         NaN
Length: 255, dtype: float64